# Generated by Django 5.1.4 on 2024-12-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LNDiccionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LNPatron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patron', models.CharField(max_length=255)),
                ('consultasql', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('zona', models.CharField(max_length=50)),
                ('ndormitorios', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tamano', models.IntegerField()),
                ('extras', models.CharField(max_length=255)),
                ('foto', models.ImageField(upload_to='fotos/')),
            ],
        ),
    ]
