# Generated by Django 5.1.4 on 2024-12-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos/'),
        ),
    ]
