# Generated by Django 5.1.4 on 2024-12-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0003_remove_vivienda_foto_vivienda_foto_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lndiccionario',
            old_name='palabra',
            new_name='campo',
        ),
        migrations.AddField(
            model_name='lndiccionario',
            name='condicion',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lndiccionario',
            name='patron',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
