# Generated by Django 5.1.4 on 2024-12-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0004_rename_palabra_lndiccionario_campo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lndiccionario',
            name='condicion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
